### PR TITLE
Minimal working example

### PR DESCRIPTION
**Pull request by rushiagr**
GET and POST request works. Fetching from and putting to database also works.

### CODE REVIEW

**Comment by chirag200666** [comment]
A custom defined class named UserInfo has been used for storing username and password, I would like to propose using Django's internal authentication mechanism( django.contrib.auth ), which is more secure and takes care of things like encrypting the passwords.

**Comment by ajayaa** [comment]
chirag200666, As I understand this is done only for testing purpose or you can say playing around with Django. This is probably going to be removed. The plan is to authenticate using google Oauth2. Please see google-auth directory for a small demo of google authentication. Additionally read the commit message for more info on how to try out google-auth. You can optionally update README.md if you are successful with trial of google-auth.

**Comment by rushiagr** [comment]
@chirag200666 First of all, thanks for interest into this project :+1: :)

As @ajayaa said, it's only for testing purposes. We're going to use OAuth. @ajayaa probably we should create a separate issue which will describe how we are imagining the solution using google oauth. I'll write one up maybe today..

**Comment by chirag200666** [comment]
@rushiagr , I am interested in contributing to the project. It would be great to collaborate. :+1: 
I was thinking of two login interfaces, one with Google oauth and the other without it. Only implementing Oauth will be smooth for users. 
I had a talk with @ajayaa today, how about we write more features required for the portal.

**Comment by ajayaa** [comment]
@rushiagr  @chirag200666 I would suggest to create a separate repo for creating specifications where people can elaborate their ideas with diagrams(if needed) and what not. This way someone could go through the history of project very quickly. It would be good to get a clear idea of what is there in the mind of developer. It would also force the developer to think through the idea.

The name of repo could be something like alumni-portal-spec.

**Pull request merged**
