### PR TITLE
Created Models and views required for a person to register, edit his contact info.

### PR DESCRIPTION
**Pull request by chirag200666**
Created models for Department, Degree, Userinfo. 
Dml file to populate department and degree data.
Create, view, update the Unserinfo model.

### CODE REVIEW

**Comment by chirag200666** [comment]
for update profile to work in portalapp/view.py line no 59 should be
template_name_suffix = '_form'
Can't push more than one pull request.

**Comment by rushiagr** [comment]
South is not required as django's latest version now has migrations support built-in

**Comment by rushiagr** [comment]
I'll review the code tomorrow, but just looking at the commit messages, I must say great work. Thank you for that :)

**Comment by chirag200666** [comment]
@rushiagr  for the south commit, yeah it was unintentional, I don't know why that super old commit came in this pull request. the new inbuilt migration is pretty cool. 
Tomorrow would be awesome. :smile: 
and welcome,  was just enjoying Django and weekend. :+1:

**Comment by ajayaa** [comment]
@chirag200666 

The auth module works nicely now. Non iith mails can't authenticate.

* The search page is open. Even without authentication you can go search for a user. What is the link  between /search and /searchname ?
* When I ran python "manage.py shell < portalapp/dml.py" it gives me an error saying that "OperationalError: no such table: portalapp_department". Does that mean I would have to create the table manually?

**Comment by rushiagr** [comment]
@ajayaa did you do `python manage.py migrate`?

**Comment by ajayaa** [comment]
@rushiagr Am I supposed to run "python manage.py migrate"? I thought what @chirag200666 mentioned in the commit message is another way to do it?

**Comment by chirag200666** [comment]
@ajayaa 
* dml.py just has rows to be added for departments and degrees. Tables have to added to database for these rows to be added by the migration feature of django.
* Regarding the position of templates, putting them in the main folder or under the apps is just a matter of preference. Personally I prefer to keep them in the app folder itself, as I felt it is easier to manage that way.
http://www.revsys.com/blog/2014/nov/21/recommended-django-project-layout/
http://stackoverflow.com/questions/22841764/best-practice-for-django-project-working-directory-structure
*  Adding login to internal pages like search, we will start doing that from now on.
*  As you suggested we will add the required js files in the bootstrap.sh, in future we can explore adding the js files to the project itself, as there are not too many external js, css files.

**Comment by ajayaa** [comment]
@chirag200666 Please remove some pdb statements present in your code. Also rename reference of  handlebars.js to handlebars-v3.0.0.js

Other than that looks good.

**Comment by chirag200666** [comment]
would it not be better to name it handlebars.js as we have done for jquery and others, so even if the new version available which might be handlebars-v3.1.0.js the includes at all places need not be changed and the application will still work ?

I think I removed the last pdb comment in this commit : https://github.com/chirag200666/alumni-portal/commit/f3c1848f6eeb14661ac6a17f030c2b84c7654469 about an hour ago, can you pull from there and confirm.

and were you able to view and edit your profile ?

**Pull request merged**
